apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc-b.fullname" . }}
  labels: {{- include "svc-b.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "svc-b.selectorLabels" . | nindent 4 }}
