{{- if and (eq "dynamodb" .Values.app.persistence.provider) .Values.dynamodb.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc-a.dynamodb.fullname" . }}
  labels:
    {{- include "svc-a.dynamodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dynamodb.service.type }}
  ports:
    - port: {{ .Values.dynamodb.service.port }}
      targetPort: dynamodb
      protocol: TCP
      name: dynamodb
  selector:
    {{- include "svc-a.dynamodb.selectorLabels" . | nindent 4 }}
{{- end }}